apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: {{ .Values.global.gcpProject }}
  # StorageBucket names must be globally unique. Replace ${PROJECT_ID?} with your project ID.
  name: {{ .Values.global.gcpProject }}-neo4j-backups